[workspace]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
name = "2025-12-16_BetterDataFormatsforFasterAnalysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
openpyxl = ">=3.1.5,<4"
xlsxwriter = ">=3.2.9,<4"
pyarrow = ">=22.0.0,<23"
parquet-tools = ">=0.2.16,<0.3"
thriftpy2 = ">=0.5.3,<0.6"
